### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ghost** [JadedPacks/Magic-Farm-2#1]
- [ ] Double check all configs
- [ ] Update MT scripts
- [ ] Add NEI hide scripts
- [ ] Generate JadedLibs json
- [ ] Fix duplicate ID's with newer mods
- [ ] Double check spelling and grammar in jc_magicfarmstart.xml book (@Remclave)

**Comment by KlyukinSA** [comment]
hello. i don't understand what any of your checkitems mean. nevertheless i have error with recipe of flint. 4 gravel gives weird gravel bricks instead
